# -*- coding: utf-8 -*-
"""cnn-model.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fg3kRGp4JIffKu3ryrD-WWt01hmdFr1P
"""

from tensorflow.keras import layers, models

# Define a simple CNN model
model = models.Sequential()

# Input Layer
model.add(layers.InputLayer(input_shape=(128, 128, 3)))

# Convolutional Layer 1
model.add(layers.Conv2D(32, (3, 3), activation='relu'))
model.add(layers.MaxPooling2D((2, 2)))

# Convolutional Layer 2
model.add(layers.Conv2D(64, (3, 3), activation='relu'))
model.add(layers.MaxPooling2D((2, 2)))

# Convolutional Layer 3
model.add(layers.Conv2D(128, (3, 3), activation='relu'))
model.add(layers.MaxPooling2D((2, 2)))

# Flatten and Fully Connected Layer
model.add(layers.Flatten())
model.add(layers.Dense(128, activation='relu'))

# Output Layer
model.add(layers.Dense(1, activation='sigmoid'))  # Binary classification

# Compile the Model
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.summary()